// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAur2Bqq6mz5MD_Qgajf1HlZyEW66rr-Tc',
    appId: '1:957710477110:web:eedeff661a97511bedb597',
    messagingSenderId: '957710477110',
    projectId: 'al-tarqea-finance',
    authDomain: 'al-tarqea-finance.firebaseapp.com',
    storageBucket: 'al-tarqea-finance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfUU1Glui4cPeOXDYWXZZNOESbUqrQ4AA',
    appId: '1:957710477110:android:2c5819a4be430902edb597',
    messagingSenderId: '957710477110',
    projectId: 'al-tarqea-finance',
    storageBucket: 'al-tarqea-finance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlKqL4ro931OChSSZtzZ2wx1y8bV60QA0',
    appId: '1:957710477110:ios:f152538a533108a4edb597',
    messagingSenderId: '957710477110',
    projectId: 'al-tarqea-finance',
    storageBucket: 'al-tarqea-finance.firebasestorage.app',
    iosBundleId: 'com.karam.alTarqeaFinance',
  );

}